import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Activity, ArrowRight, BadgeCheck, CalendarDays, CheckCircle2, ChevronDown, Dna, FlaskConical, HeartPulse, Home, Instagram, MapPin, Menu, MessageCircle, Microscope, Navigation, Phone, ShieldCheck, Star, Stethoscope, TestTube2, X } from "lucide-react";

export const Route = createFileRoute("/")({ component: Index });
const WHATSAPP="https://wa.me/5522992778140?text=Ol%C3%A1!%20Gostaria%20de%20agendar%20um%20atendimento%20na%20Cl%C3%ADnica%20M%C3%A9dica%20Pedrosa.";
const exams=[
 [Activity,"Hemograma completo","Avaliação das células do sangue para investigação e acompanhamento."],[FlaskConical,"Glicemia","Medição da glicose para acompanhamento metabólico."],[TestTube2,"Perfil lipídico","Colesterol total, HDL, LDL e triglicerídeos."],[Microscope,"Exames hormonais","Dosagens hormonais para diferentes necessidades clínicas."],[HeartPulse,"Função hepática","Avaliações que auxiliam no acompanhamento do fígado."],[ShieldCheck,"Função renal","Exames importantes para acompanhar a saúde dos rins."],[Activity,"Beta HCG","Exame laboratorial para identificação e acompanhamento da gestação."],[Dna,"Vitaminas e minerais","Dosagens de nutrientes importantes para o organismo."]
];
const services=[[Microscope,"Exames laboratoriais","Coletas e análises com organização e orientação."],[Home,"Coleta domiciliar","Mais comodidade no conforto da sua casa."],[Stethoscope,"Clínica médica","Avaliação, prevenção e acompanhamento da saúde."],[CalendarDays,"Check-up","Rotina de exames para acompanhamento preventivo."]];
const team=["https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=900&q=85","https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=85","https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=900&q=85"];
const testimonials=["Atendimento atencioso e uma equipe que explica tudo com muita clareza.","Gostei muito da organização e da facilidade para realizar meus exames.","A coleta domiciliar facilitou muito minha rotina. Atendimento cuidadoso e prático.","Um lugar onde você percebe cuidado desde a chegada. Profissionais muito atenciosos."];
const faq=[["Quais exames laboratoriais vocês realizam?","Trabalhamos com diversos exames de análises clínicas. Fale conosco para confirmar um exame específico."],["Vocês fazem coleta domiciliar?","Sim. Consulte pelo WhatsApp disponibilidade, condições e orientações para seu endereço."],["Preciso agendar para fazer exames?","Recomendamos entrar em contato antes para confirmar preparo, horário e disponibilidade."],["Vocês atendem convênios?","Trabalhamos com diferentes planos e convênios. A cobertura varia conforme o plano e procedimento."],["Como saber se preciso de jejum?","O preparo depende do exame. Nossa equipe informa exatamente o que é necessário antes da coleta."],["Onde fica a Clínica Médica Pedrosa?","Estamos em Âncora, no Rio de Janeiro. Use o mapa para abrir a rota."]];
const partners=["Unimed","NotreDame Intermédica","Amil","GEAP Saúde","Porto Seguro","Bradesco Saúde","CASSI"];

function Index(){
 const [menu,setMenu]=useState(false); const [open,setOpen]=useState<number|null>(0);
 return <main className="pedrosa-site">
 <header className="topbar"><div className="container nav-wrap"><a href="#inicio" className="brand"><span className="brand-mark"><Dna/></span><span><strong>PEDROSA</strong><small>LABS • CLÍNICA MÉDICA</small></span></a><nav className={menu?"main-nav open":"main-nav"}><a href="#exames" onClick={()=>setMenu(false)}>Exames</a><a href="#servicos" onClick={()=>setMenu(false)}>Serviços</a><a href="#equipe" onClick={()=>setMenu(false)}>Equipe</a><a href="#convenios" onClick={()=>setMenu(false)}>Convênios</a><a href="#localizacao" onClick={()=>setMenu(false)}>Localização</a><a href="#faq" onClick={()=>setMenu(false)}>Dúvidas</a></nav><a className="nav-cta" href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle/> Agendar</a><button className="menu-toggle" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>

 <section className="hero" id="inicio"><div className="hero-orb one"/><div className="hero-orb two"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><i/> CUIDADO E CONFIANÇA PARA SUA SAÚDE</div><h1>Saúde acompanhada de perto, <span>com confiança.</span></h1><p>Exames laboratoriais, atendimento médico e coleta domiciliar em um só lugar. Uma equipe preparada para cuidar de você com atenção em cada etapa.</p><div className="hero-actions"><a className="btn btn-primary" href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle/> Agendar pelo WhatsApp <ArrowRight/></a><a className="btn btn-light" href="#exames">Conhecer exames</a></div><div className="hero-trust"><span><BadgeCheck/> Atendimento humanizado</span><span><ShieldCheck/> Cuidado e segurança</span><span><Home/> Coleta domiciliar</span></div></div><div className="hero-visual"><div className="hero-main-img"><img src="https://images.unsplash.com/photo-1579154204601-01588f351d1d?auto=format&fit=crop&w=1200&q=90" alt="Profissional em laboratório"/></div><div className="hero-small-img"><img src="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=700&q=85" alt="Análises clínicas"/></div><div className="hero-stat"><FlaskConical/><span><b>Exames com cuidado</b><small>Da coleta ao resultado</small></span></div><div className="hero-brand-card"><Dna/><span><b>PEDROSA</b><small>LABS</small></span></div></div></div></section>
 <div className="info-strip"><div className="container strip-track"><span><CheckCircle2/> Exames laboratoriais</span><span><Home/> Coleta domiciliar</span><span><Stethoscope/> Clínica médica</span><span><ShieldCheck/> Atendimento cuidadoso</span><span><CalendarDays/> Agendamento fácil</span></div></div>

 <section className="section intro"><div className="container split"><div><label>POR QUE A PEDROSA?</label><h2>Mais do que exames. <span>Um cuidado completo.</span></h2></div><div><p>Da prevenção ao acompanhamento, a Clínica Médica Pedrosa reúne estrutura, profissionais e serviços para tornar sua jornada de saúde mais simples.</p><a className="text-link" href={WHATSAPP} target="_blank" rel="noreferrer">Falar com nossa equipe <ArrowRight/></a></div></div></section>

 <section className="section services" id="servicos"><div className="container"><div className="heading"><div><label>NOSSOS SERVIÇOS</label><h2>Cuidados para diferentes <span>momentos da sua saúde.</span></h2></div><a className="btn btn-primary small" href={WHATSAPP} target="_blank" rel="noreferrer">Agendar atendimento <ArrowRight/></a></div><div className="service-grid">{services.map(([I,t,d])=><article className="service-card" key={t as string}><div className="icon-box"><I/></div><h3>{t as string}</h3><p>{d as string}</p><a href={WHATSAPP} target="_blank" rel="noreferrer">Agendar <ArrowRight/></a></article>)}</div></div></section>

 <section className="section exams" id="exames"><div className="container"><div className="heading centered"><div><label>EXAMES LABORATORIAIS</label><h2>Precisão para você <span>cuidar da sua saúde.</span></h2><p>Alguns dos exames disponíveis no laboratório Pedrosa. Para preparo, valores e disponibilidade, fale com nossa equipe.</p></div></div><div className="marquee"><div className="exam-track">{[...exams,...exams].map(([I,t,d],i)=><article className="exam-card" key={(t as string)+i}><div className="exam-icon"><I/></div><h3>{t as string}</h3><p>{d as string}</p><a href={WHATSAPP} target="_blank" rel="noreferrer">Consultar exame <ArrowRight/></a></article>)}</div></div><div className="center-cta"><a className="btn btn-primary" href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle/> Quero consultar meus exames</a></div></div></section>

 <section className="section collection"><div className="container collection-grid"><div className="collection-photo"><img src="https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1100&q=85" alt="Atendimento em saúde"/><div className="collection-badge"><Home/><b>Coleta em casa</b><small>Mais praticidade para você</small></div></div><div><label>COLETA DOMICILIAR</label><h2>Seu exame sem precisar <span>sair de casa.</span></h2><p>Se deslocar até o laboratório nem sempre é simples. A Pedrosa oferece coleta domiciliar com mais conforto e praticidade para sua rotina.</p><div className="checks"><span><CheckCircle2/> Atendimento no conforto da sua casa</span><span><CheckCircle2/> Praticidade para idosos e famílias</span><span><CheckCircle2/> Agendamento pelo WhatsApp</span><span><CheckCircle2/> Orientações antes da coleta</span></div><a className="btn btn-primary" href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle/> Solicitar coleta domiciliar</a></div></div></section>

 <section className="section gallery"><div className="container"><div className="heading centered"><div><label>NOSSO ESPAÇO</label><h2>Um ambiente pensado para <span>receber você bem.</span></h2></div></div><div className="gallery-grid"><img src="https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1100&q=85" alt="Ambiente de atendimento"/><img src="https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=85" alt="Ambiente clínico"/><img src="https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=85" alt="Estrutura médica"/><img src="https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=85" alt="Profissionais de saúde"/></div><div className="center-cta"><a className="btn btn-dark" href={WHATSAPP} target="_blank" rel="noreferrer">Agendar atendimento <ArrowRight/></a></div></div></section>

 <section className="section team" id="equipe"><div className="container"><div className="heading"><div><label>NOSSA EQUIPE</label><h2>Pessoas que cuidam <span>de pessoas.</span></h2></div><p>Profissionais preparados para oferecer um atendimento atento, respeitoso e acolhedor.</p></div><div className="team-grid">{team.map((img,i)=><article className="team-card" key={img}><img src={img} alt={`Equipe Pedrosa ${i+1}`}/><div><h3>{["Equipe médica","Equipe de laboratório","Atendimento Pedrosa"][i]}</h3><p>{["Clínica Médica Pedrosa","Análises clínicas","Acolhimento e orientação"][i]}</p><span><BadgeCheck/> Atendimento humanizado</span></div></article>)}</div><div className="center-cta"><a className="btn btn-primary" href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle/> Agendar atendimento</a></div></div></section>

 <section className="section partners" id="convenios"><div className="container"><div className="heading centered"><div><label>CONVÊNIOS E PARCEIROS</label><h2>Facilidade para cuidar <span>da sua saúde.</span></h2><p>Confira alguns dos convênios apresentados pela Pedrosa. A cobertura pode variar conforme o plano e procedimento.</p></div></div><div className="partner-marquee"><div className="partner-track">{[...partners,...partners].map((p,i)=><div className="partner" key={p+i}><Dna/> {p}</div>)}</div></div><div className="center-cta"><a className="btn btn-primary" href={WHATSAPP} target="_blank" rel="noreferrer"><Phone/> Confirmar meu convênio</a></div></div></section>

 <section className="section testimonials"><div className="container"><div className="heading centered"><div><label>EXPERIÊNCIA DE QUEM CONFIA</label><h2>Seu cuidado também começa <span>pela confiança.</span></h2></div></div><div className="marquee"><div className="testimonial-track">{[...testimonials,...testimonials].map((t,i)=><article className="testimonial" key={i}><div className="stars">{[1,2,3,4,5].map(n=><Star key={n} fill="currentColor"/>)}</div><p>“{t}”</p><strong>Paciente Pedrosa</strong><small>Experiência com a Clínica Médica Pedrosa</small></article>)}</div></div><div className="center-cta"><a className="btn btn-primary" href={WHATSAPP} target="_blank" rel="noreferrer">Quero ser atendido <ArrowRight/></a></div></div></section>

 <section className="section location" id="localizacao"><div className="container location-grid"><div><label>ONDE ESTAMOS</label><h2>Venha nos visitar em <span>Âncora.</span></h2><p>Encontre a Clínica Médica Pedrosa no mapa e abra a rota para chegar com facilidade.</p><div className="location-item"><MapPin/><span><b>Laboratório de Análises Clínicas e Clínica Médica Pedrosa</b><small>Âncora • Rio de Janeiro</small></span></div><div className="location-item"><Phone/><span><b>(22) 99277-8140</b><small>Também: (22) 99256-2444</small></span></div><div className="location-actions"><a className="btn btn-primary" href="https://www.google.com/maps/search/?api=1&query=Laborat%C3%B3rio%20Pedrosa%20%C3%82ncora%20RJ" target="_blank" rel="noreferrer"><Navigation/> Abrir no Google Maps</a><a className="btn btn-outline" href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp</a></div></div><div className="map"><iframe title="Localização Pedrosa" src="https://www.google.com/maps?q=Laborat%C3%B3rio%20Pedrosa%20%C3%82ncora%20RJ&output=embed" loading="lazy"/></div></div></section>

 <section className="section faq" id="faq"><div className="container faq-grid"><div><label>PERGUNTAS FREQUENTES</label><h2>Antes de vir, <span>tire suas dúvidas.</span></h2><p>Não encontrou o que procura? Nossa equipe está pronta para orientar você.</p><a className="btn btn-primary" href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle/> Perguntar pelo WhatsApp</a></div><div className="faq-list">{faq.map(([q,a],i)=><div className={open===i?"faq-item active":"faq-item"} key={q}><button onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><ChevronDown/></button>{open===i&&<p>{a}</p>}</div>)}</div></div></section>

 <section className="final"><div className="container final-inner"><div><label>CLÍNICA MÉDICA PEDROSA</label><h2>Cuide da sua saúde com <span>mais tranquilidade.</span></h2><p>Agende seus exames, tire suas dúvidas ou consulte a disponibilidade da coleta domiciliar.</p></div><a className="btn btn-white" href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle/> Agendar pelo WhatsApp <ArrowRight/></a></div></section>
 <footer className="footer"><div className="container footer-grid"><div><a href="#inicio" className="brand"><span className="brand-mark"><Dna/></span><span><strong>PEDROSA</strong><small>LABS • CLÍNICA MÉDICA</small></span></a><p>Cuidado e confiança para sua saúde.</p></div><div><b>Atendimento</b><a href={WHATSAPP} target="_blank" rel="noreferrer">WhatsApp: (22) 99277-8140</a><span>(22) 99256-2444</span></div><div><b>Localização</b><span>Âncora • Rio de Janeiro</span><a href="#localizacao">Ver mapa</a></div><div><b>Redes sociais</b><a href="https://www.instagram.com/laboratorio.pedrosa/" target="_blank" rel="noreferrer"><Instagram/> Instagram</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Pedrosa Labs • Clínica Médica</span><a href="#inicio">Voltar ao topo ↑</a></div></footer>
 <a className="floating-whatsapp" href={WHATSAPP} target="_blank" rel="noreferrer" aria-label="WhatsApp"><MessageCircle/></a>
 </main>
}
